name: Audit

on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  audit:
    name: "Audit"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        id: actions-rs
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Audit
        run: |
          cargo install cargo-audit
          cargo audit
